#ifndef OSCILLOSCOPELED_H_
#define OSCILLOSCOPELED_H_

#include "stm32f4xx_conf.h"

#define OSC_LED_TRIGGER_GPIO_PORT       GPIOC
#define OSC_LED_TRIGGER_GPIO_PIN        GPIO_Pin_6
#define OSC_LED_TRIGGER_GPIO_CLK        RCC_AHB1Periph_GPIOC

#define OSC_LED_RANGE_PLUS_GPIO_PORT    GPIOA
#define OSC_LED_RANGE_PLUS_GPIO_PIN     GPIO_Pin_3
#define OSC_LED_RANGE_PLUS_GPIO_CLK     RCC_AHB1Periph_GPIOA

#define OSC_LED_RANGE_MINUS_GPIO_PORT   GPIOA
#define OSC_LED_RANGE_MINUS_GPIO_PIN    GPIO_Pin_8
#define OSC_LED_RANGE_MINUS_GPIO_CLK    RCC_AHB1Periph_GPIOA

#define OSC_LED_CHANNEL_A_GPIO_PORT     GPIOE
#define OSC_LED_CHANNEL_A_GPIO_PIN      GPIO_Pin_6
#define OSC_LED_CHANNEL_A_GPIO_CLK      RCC_AHB1Periph_GPIOE

#define OSC_LED_CHANNEL_B_GPIO_PORT     GPIOE
#define OSC_LED_CHANNEL_B_GPIO_PIN      GPIO_Pin_5
#define OSC_LED_CHANNEL_B_GPIO_CLK      RCC_AHB1Periph_GPIOE

#define OSC_LED_TRIGGER_SET()           OSC_LED_TRIGGER_GPIO_PORT->BSRRL |=  OSC_LED_TRIGGER_GPIO_PIN
#define OSC_LED_TRIGGER_CLEAR()         OSC_LED_TRIGGER_GPIO_PORT->BSRRH |=  OSC_LED_TRIGGER_GPIO_PIN
#define OSC_LED_TRIGGER_TOGGLE()        (OSC_LED_TRIGGER_GPIO_PORT->IDR & OSC_LED_TRIGGER_GPIO_PIN) ? (OSC_LED_TRIGGER_CLEAR()) : (OSC_LED_TRIGGER_SET())

#define OSC_LED_RANGE_PLUS_SET()        OSC_LED_RANGE_PLUS_GPIO_PORT->BSRRL |=  OSC_LED_RANGE_PLUS_GPIO_PIN
#define OSC_LED_RANGE_PLUS_CLEAR()      OSC_LED_RANGE_PLUS_GPIO_PORT->BSRRH |=  OSC_LED_RANGE_PLUS_GPIO_PIN
#define OSC_LED_RANGE_PLUS_TOGGLE()     (OSC_LED_RANGE_PLUS_GPIO_PORT->IDR & OSC_LED_RANGE_PLUS_GPIO_PIN) ? (OSC_LED_RANGE_PLUS_CLEAR()) : (OSC_LED_RANGE_PLUS_SET())

#define OSC_LED_RANGE_MINUS_SET()       OSC_LED_RANGE_MINUS_GPIO_PORT->BSRRL |=  OSC_LED_RANGE_MINUS_GPIO_PIN
#define OSC_LED_RANGE_MINUS_CLEAR()     OSC_LED_RANGE_MINUS_GPIO_PORT->BSRRH |=  OSC_LED_RANGE_MINUS_GPIO_PIN
#define OSC_LED_RANGE_MINUS_TOGGLE()    (OSC_LED_RANGE_MINUS_GPIO_PORT->IDR & OSC_LED_RANGE_MINUS_GPIO_PIN) ? (OSC_LED_RANGE_MINUS_CLEAR()) : (OSC_LED_RANGE_MINUS_SET())

#define OSC_LED_CHANNEL_A_SET()         OSC_LED_CHANNEL_A_GPIO_PORT->BSRRL |=  OSC_LED_CHANNEL_A_GPIO_PIN
#define OSC_LED_CHANNEL_A_CLEAR()       OSC_LED_CHANNEL_A_GPIO_PORT->BSRRH |=  OSC_LED_CHANNEL_A_GPIO_PIN
#define OSC_LED_CHANNEL_A_TOGGLE()      (OSC_LED_CHANNEL_A_GPIO_PORT->IDR & OSC_LED_CHANNEL_A_GPIO_PIN) ? (OSC_LED_CHANNEL_A_CLEAR()) : (OSC_LED_CHANNEL_A_SET())

#define OSC_LED_CHANNEL_B_SET()         OSC_LED_CHANNEL_B_GPIO_PORT->BSRRL |=  OSC_LED_CHANNEL_B_GPIO_PIN
#define OSC_LED_CHANNEL_B_CLEAR()       OSC_LED_CHANNEL_B_GPIO_PORT->BSRRH |=  OSC_LED_CHANNEL_B_GPIO_PIN
#define OSC_LED_CHANNEL_B_TOGGLE()      (OSC_LED_CHANNEL_B_GPIO_PORT->IDR & OSC_LED_CHANNEL_B_GPIO_PIN) ? (OSC_LED_CHANNEL_B_CLEAR()) : (OSC_LED_CHANNEL_B_SET())

void OSC_LED_Init(void);

#endif /* OSCILLOSCOPELED_H_ */
